### ISSUE TITLE
SRAM 512 is not DRC clean

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#7]
## Expected Behavior
`sram512x8m8wm1` DRC clean

## Actual Behavior
`sram512x8m8wm1` has a violation in rule `NW.2b_5V_`

## Steps to Reproduce the Problem

1. build the pdk
2. run `python3 run_drc.py --gf180mcu=C --path=$PDK_ROOT/$PDK/libs.ref/gf180mcu_fd_ip_sram/gds/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds`

## Specifications

- Klayout Version: 0.28
- Platform: Debian

**Comment by atorkmabrains** [comment]
@marwaneltoukhy These cells has NW.2b_5V violations as you have mentioned. This rule is one of the connectivity rules. By default, we made the rule deck more restrictive and force the most restrictive rule. To make this pass, you need to enable the connectivity version of the rule by using the following switch as shown below:
```bash
python run_drc.py --variant=C --path=/home/atork/companies/mabrains/clients/efabless/projects/gf180mcu_project/google_version/globalfoundries-pdk-ip-gf180mcu_fd_ip_sram/cells/gf180mcu_fd_ip_sram__sram512x8m8wm1/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds --connectivity --run_dir=./drc_runs
```

As you see I have added ```--connectivity``` switch and this will make the sram pass. The reason we don't enable this by default is that the connectivity checks take longer time to run due to limitation in the implementation in klayout.

I'll open an enhancement request on klayout to enable such feature.
